# Activar con: --spring.profiles.active=aws
# Reemplaza estos valores cuando creemos AWS RDS
spring.datasource.url=jdbc:postgresql://TU-ENDPOINT-RDS:5432/gymdb
spring.datasource.username=postgres
spring.datasource.password=TU_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
